# Generated by Django 5.2.15 on 2026-06-05 19:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="interest_due",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Interest that had accrued (including any carry-over) just before this payment was applied.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="interest_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="principal_balance_after",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="principal_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="balance_after",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Principal remaining plus any unpaid carried interest right after this payment.",
                max_digits=12,
            ),
        ),
    ]
