# Generated by Django 5.2.15 on 2026-06-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="term_months",
            field=models.PositiveIntegerField(
                help_text="Expected loan duration. Tracking only — does not affect interest math."
            ),
        ),
    ]
